console.log("Hello World")
console.log(" I will see if this is possible: hi there")
console.log("hi there I like your makeup")
console.log("I am tired: this is definately harder than i thought we definately have to look for working solution")
console.log("hello! Welcome to the planet earth")
